<?php
/**
 *
 * @author        Krunal Padmashali <kp@cloudlab.at>.
 * @copyright     Copyright(c) 2020 CloudLab AG (https://cloudlab.ag)
 * @link          https://cloudlab.ag/
 * @date          07/01/2021
 */

/** @var $block \Printq\CheckoutFields\Block\Adminhtml\CustomField\Edit\Options\Options */

$stores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="admin__fieldset fieldset">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Options (Values of Your Field)')) ?></span>
    </legend><br />
    <div class="admin__control-table-wrapper" id="manage-options-panel" data-index="customfield_options_select_container">
        <table class="admin__control-table" data-index="customfield_options_select">
            <thead>
                <tr id="customfield-options-table">
                    <th class="col-draggable"></th>
                    <th class="col-default control-table-actions-th">
                        <span><?= $block->escapeHtml(__('Is Default')) ?></span>
                    </th>
                    <?php
                    foreach ($stores as $_store) :?>
                        <th<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) :?> class="_required"<?php endif; ?>>
                            <span><?= $block->escapeHtml(__($_store->getName())) ?></span>
                        </th>
                    <?php endforeach;
                    $storetotal = count($stores) + 3;
                    ?>
                    <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?= (int)$storetotal ?>" class="validation">
                    <input type="hidden" class="required-dropdown-customfield-entry" name="dropdown_customfield_validation"/>
                    <input type="hidden" class="required-dropdown-customfield-unique" name="dropdown_customfield_validation_unique"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?= (int) $storetotal ?>" class="col-actions-add">
                    <button id="add_new_option_button" data-action="add_new_row"
                                    title="<?= $block->escapeHtml(__('Add Option')) ?>"
                                    type="button" class="action- scalable add">
                        <span><?= $block->escapeHtml(__('Add Option')) ?></span>
                    </button>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
    <script id="row-template" type="text/x-magento-template">
        <tr <% if (data.rowClasses) { %>class="<%- data.rowClasses %>"<% } %>>
            <td class="col-draggable">
                <div data-role="draggable-handle" class="draggable-handle" title="<?= $block->escapeHtml(__('Sort Option')) ?>">
                </div>
                <input data-role="order" type="hidden" name="option[order][<%- data.id %>]"  value="<%- data.sort_order %>"/>
            </td>
            <td class="col-default control-table-actions-cell">
                <input class="input-radio" type="<%- data.intype %>" name="default[]" value="<%- data.id %>" <%- data.checked %>/>
            </td>
            <?php foreach ($stores as $_store) :?>
            <td class="col-<%- data.id %>"><input name="option[value][<%- data.id %>][<?= (int) $_store->getId() ?>]" value="<%- data.store<?= /* @noEscape */ (int) $_store->getId() ?> %>" class="input-text<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) :?> required-option required-unique<?php endif; ?>" type="text"/></td>
            <?php endforeach; ?>
            <td id="delete_button_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
                <button id="delete_button_<%- data.id %>" title="<?= $block->escapeHtml(__('Delete')) ?>" type="button" class="action- scalable delete delete-option">
                    <span><?= $block->escapeHtml(__('Delete')) ?></span>
                </button>
            </td>
        </tr>
    </script>
    <?php
    $values = [];
    foreach ($block->getOptionValues() as $value) {
        $value = $value->getData();
        $values[] = is_array($value) ? array_map(function ($str) {
            return htmlspecialchars_decode($str, ENT_QUOTES);
        }, $value) : $value;
    }
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Printq_CheckoutFields/js/options": {
                    "customfieldsData": <?= /* @noEscape */ json_encode($values, JSON_HEX_QUOT) ?>
                },
                "Printq_CheckoutFields/js/unique-validate": {
                    "element": "required-dropdown-attribute-unique",
                    "message": "<?= $block->escapeHtml(__("The value of Admin must be unique.")) ?>"
                }
            }
        }
    </script>
</fieldset>
