<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <!-- Custom Input Field -->
        <div class="field verrechnungskostenstelle required">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Verrechnungskostenstelle') ?></span></label>
            <div class="control">
                <input
                    type="text"
                    name="verrechnungskostenstelle"
                    id="verrechnungskostenstelle"
                    minlenght="5"
                    maxlength="5"
                    required=""
                    placeholder="Verrechnungskostenstelle"
                />
            </div>
        </div>
        <div class="field verrechnungskonto required">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Verrechnungskonto') ?></span></label>
            <div class="control">
                <input
                    type="text"
                    name="verrechnungskonto"
                    id="verrechnungskonto"
                    minlenght="10"
                    maxlength="10"
                    required=""
                    placeholder="Verrechnungskonto"
                />
            </div>
        </div>
        <div class="field bemerkung">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Bemerkung') ?></span></label>
            <div class="control">
                <input
                    type="text"
                    name="bemerkung"
                    id="bemerkung"
                    maxlength="1500"
                    placeholder="Bemerkung"
                />
            </div>
        </div>
        <div class="field wunschtermin required">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Wunschtermin') ?></span></label>
            <div class="control">
                <input
                    type="date"
                    name="wunschtermin"
                    id="wunschtermin"
                    required=""
                />
            </div>
        </div>
        <!-- Custom Input Field -->
        <br>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>